version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: youtube_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: youtube
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: youtube_redis
    restart: always
    ports:
      - "6379:6379"

  poller:
    build: .
    container_name: youtube_poller
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgres://postgres:admin@postgres:5432/youtube
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/app
    command: ["node", "src/fetchData.js"]

  api:
    build: .
    container_name: youtube_api
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgres://postgres:admin@postgres:5432/youtube
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: ["node", "src/server.js"]

volumes:
  pgdata:
