services:
  postgres:
    image: postgres:15
    container_name: youtube_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: youtube
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: youtube_poller
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgres://postgres:admin@postgres:5432/youtube
    volumes:
      - .:/usr/src/app
    command: ["node", "src/fetchData.js"]

volumes:
  pgdata:
